dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-11/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: oDcEvkiukEp2bAj+DUZ+3uD+KQAQJPA7fBUWu3f4gl5sEGgxB/FH8lMi1GxgeIPwkv4rtJVQuveOMIEA2MFDCe0wHksMk6FzNkfWD3xXqOl2fmNA/K8vNyMvGaRZ5p5J97witYbk5oNMh//qOGadd6do4Xwe+LC0Z8e+VRLJc2jeMTt2w3gvXyD73E4UbvkHwXsQPtQ3fj4zKEZbInbaoUOnk/3oD/0PtwZ3FK40UWmE8HHRsIMA9c7W+fxkA08HlHaieXWOr6QUkWxH1isUX7VqjVUl0LKNqecgMeCIxzsOmSmn1BLAW/Xpr6avnoyIGVQr11f8iWYU3j83lsl8oKMr+JU+aoXgM6T1YRVcs1Z+HG8M4Tc+bTBaRwpE3yr0wq2rxLsCl7TFqz8DBG35SDDiM0QltchQDgDAMDkdXacek3SJlmJg46glWxriRx0EI7ufwcQkSxz4lsQrxuCW9B1TqQ9ZCFR6DQsYVLIDf6oVcbMMFoSlXFjcRRuPzredoIkbi48vVVYVuV2JLTl6XP+DP5zYRhPwXvnCK+thXKeQZwOivYLuk8snnvqb7+bxxTi7NKnaKgDcM6DJeaETr53O4raZvDbR/tBQv9Urvqt78gmA01eoI3LkE3GZPQCpsmlqKHU24VIQ+x8qpcS89Lp8jq9qk0lZYuxv5WOvSlE=
